Upgrade to ^1.0.0 of Jupyter Book
This is to get around a 3.13 incompatibility with the version of `click`
`jupyter-book` was using under the hood that used a feature deprecated
by Python3.13, specifically to get us around:

```
  File "/usr/local/lib/python3.13/site-packages/jupyter_book/cli/pluggable.py", line 13, in get_entry_point_names
    return [ep.name for ep in metadata.entry_points().get(group, [])]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

Update: ensure Typer version for this package is up-to-date as well